obstacle_range: 1.5
raytrace_range: 2.0
footprint: [[0.1, -0.3], [0.1, 0.3], [-0.8, 0.3], [-0.8, -0.3]]

inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

